//
// Person.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Person: JSONEncodable {
    public var fullName: String?
    public var phone: String?
    public var age: Int32?
    public var company: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["fullName"] = self.fullName
        nillableDictionary["phone"] = self.phone
        nillableDictionary["age"] = self.age?.encodeToJSON()
        nillableDictionary["Company"] = self.company
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
